name: Build

on:
  pull_request:
  push:
    branches: [$default-branch]

permissions:
  contents: read

jobs:
  # hub-stage: build
  build:
    uses: ExperienceQuality/.github/.github/workflows/node-library-build.yml@v1
    with:
      node-version: "24"
      package-manager: npm
      working-directory: .

